#北京时间8-16时每小时调用一次（周日不启动）
name: Auto Api Pro

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '0 0,1,2,3,4,5,6,7,8, * * 1-6'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install requests and nacl #安装requests模块
      run: |
        pip3 install requests
    - name: run api #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息(修改以下，复制增加账号)
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        #如此类推，自己复制增加账号/应用
        #MS_TOKEN_n: ${{ secrets.MS_TOKEN_n }} 
        #CLIENT_ID_n: ${{ secrets.CLIENT_ID_n }}
        #CLIENT_SECRET_n: ${{ secrets.CLIENT_SECRET_n }}
      run: |
        python3 runapi.py
