#每小时调用一次（996时间表）
name: Auto Api Pro

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 1-13 * * 1-6'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: Install requests and nacl #安装requests模块
      run: |
        pip3 install requests
    - name: run api #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息(修改以下，复制增加账号)
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        #如此类推，自己复制增加账号/应用
        #MS_TOKEN_n: ${{ secrets.MS_TOKEN_n }} 
        #CLIENT_ID_n: ${{ secrets.CLIENT_ID_n }}
        #CLIENT_SECRET_n: ${{ secrets.CLIENT_SECRET_n }}
      run: |
        python3 runapi.py
